### ISSUE TITLE
Adding software developed by the Workflow Systems Group

### ISSUE THREAD

**Issue by anagainaru** [ORNL/software-catalog#3]
ADIOS2
[https://github.com/ornladios/ADIOS2](https://github.com/ornladios/ADIOS2)
should be added in the categories:
- data management 
- data analysis and visualization
- accelerated performance computing

MGARD
[https://github.com/CODARcode/MGARD](https://github.com/CODARcode/MGARD)
should be added in the categories:
- data management
- data science and machine learning
- algorithmic inovation

EFFIS
[https://github.com/wdmapp/effis](https://github.com/wdmapp/effis)
should be added in the categories:
- data management 
- data analysis and visualization
- federated and autonomous systems

Let me know if you need anything else

**Comment by jarrah42** [comment]
Hi Ana, you add these to the projects yourself. If you click on the gear icon next to “About” on the project, you’ll see a field where you can enter topics. Just add these and next time the scraper runs it will put the projects into the correct categories.

**Comment by anagainaru** [comment]
@jarrah42 Before I can set the categories, the repos still need to be added. Should I modify the `software-catalog/_explore/input_lists.json` file to include the three repos I mentioned in the Issue description?

I assume I add them to this list:
```json
"repos": [
"arborx/arborx",
"kokkos/kokkos",
"qmcpack/qmcpack"
]
```

**Comment by jarrah42** [comment]
I’ve added these repos to the catalog so you should be good to go now.
